# Generated by Django 4.1.2 on 2022-10-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_alter_scrapeddata_accomodation_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapeddata',
            old_name='name_of_isting',
            new_name='name_of_listing',
        ),
        migrations.AlterField(
            model_name='rating_field',
            name='accuracy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rating_field',
            name='checkIn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rating_field',
            name='cleanliness',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rating_field',
            name='communication',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rating_field',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
